[ -f /opt/boxen/env.sh ] && source /opt/boxen/env.sh
source ~/.dotfiles/env
source ~/.dotfiles/config

google() {
 open /Applications/Google\ Chrome.app/ "http://www.google.com/search?q= $1"
}

md() {
 mkdir $1; cd $1
}